---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-gitops-config
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/advanced-cluster-management/config/overlays/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      allowEmpty: true
