apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - managedclustersetbinding.yaml
  - placement.yaml
  - gitopscluster.yaml
  - openshift-gitops-policy.yaml
